"""initial_schema

Revision ID: 0091e68d2791
Revises: 
Create Date: 2025-12-03 16:43:29.577752

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0091e68d2791'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('jigs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('codigo_qr', sa.String(length=50), nullable=False),
    sa.Column('numero_jig', sa.String(length=20), nullable=False),
    sa.Column('tipo', sa.String(length=20), nullable=False),
    sa.Column('modelo_actual', sa.String(length=100), nullable=True),
    sa.Column('estado', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_jigs_codigo_qr'), 'jigs', ['codigo_qr'], unique=True)
    op.create_index(op.f('ix_jigs_id'), 'jigs', ['id'], unique=False)
    op.create_table('tecnicos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario', sa.String(length=50), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('numero_empleado', sa.String(length=20), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('firma_digital', sa.Text(), nullable=True),
    sa.Column('turno_actual', sa.String(length=20), nullable=True),
    sa.Column('tipo_tecnico', sa.String(length=50), nullable=True),
    sa.Column('tipo_usuario', sa.String(length=20), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tecnicos_id'), 'tecnicos', ['id'], unique=False)
    op.create_index(op.f('ix_tecnicos_numero_empleado'), 'tecnicos', ['numero_empleado'], unique=True)
    op.create_index(op.f('ix_tecnicos_usuario'), 'tecnicos', ['usuario'], unique=True)
    op.create_table('auditoria_pdfs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre_archivo', sa.String(length=255), nullable=False),
    sa.Column('ruta_archivo', sa.String(length=500), nullable=False),
    sa.Column('modelo', sa.String(length=100), nullable=True),
    sa.Column('tecnico_id', sa.Integer(), nullable=False),
    sa.Column('tecnico_nombre', sa.String(length=100), nullable=False),
    sa.Column('numero_empleado', sa.String(length=20), nullable=False),
    sa.Column('fecha', sa.DateTime(), nullable=False),
    sa.Column('fecha_dia', sa.Integer(), nullable=False),
    sa.Column('fecha_mes', sa.Integer(), nullable=False),
    sa.Column('fecha_anio', sa.Integer(), nullable=False),
    sa.Column('turno', sa.String(length=20), nullable=False),
    sa.Column('linea', sa.String(length=50), nullable=True),
    sa.Column('cantidad_validaciones', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['tecnico_id'], ['tecnicos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_auditoria_pdfs_id'), 'auditoria_pdfs', ['id'], unique=False)
    op.create_table('damaged_labels',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('modelo', sa.String(length=100), nullable=False),
    sa.Column('tipo_jig', sa.String(length=30), nullable=False),
    sa.Column('numero_jig', sa.String(length=20), nullable=True),
    sa.Column('foto', sa.Text(), nullable=True),
    sa.Column('reportado_por_id', sa.Integer(), nullable=False),
    sa.Column('estado', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['reportado_por_id'], ['tecnicos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_damaged_labels_id'), 'damaged_labels', ['id'], unique=False)
    op.create_table('jigs_ng',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('jig_id', sa.Integer(), nullable=False),
    sa.Column('tecnico_id', sa.Integer(), nullable=False),
    sa.Column('fecha_ng', sa.DateTime(), nullable=True),
    sa.Column('motivo', sa.Text(), nullable=False),
    sa.Column('categoria', sa.String(length=50), nullable=True),
    sa.Column('prioridad', sa.String(length=20), nullable=True),
    sa.Column('estado', sa.String(length=20), nullable=True),
    sa.Column('fecha_reparacion', sa.DateTime(), nullable=True),
    sa.Column('tecnico_reparacion_id', sa.Integer(), nullable=True),
    sa.Column('observaciones_reparacion', sa.Text(), nullable=True),
    sa.Column('usuario_reporte', sa.String(length=100), nullable=True),
    sa.Column('usuario_reparando', sa.String(length=100), nullable=True),
    sa.Column('comentario_reparacion', sa.Text(), nullable=True),
    sa.Column('foto', sa.Text(), nullable=True),
    sa.Column('sincronizado', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['jig_id'], ['jigs.id'], ),
    sa.ForeignKeyConstraint(['tecnico_id'], ['tecnicos.id'], ),
    sa.ForeignKeyConstraint(['tecnico_reparacion_id'], ['tecnicos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_jigs_ng_id'), 'jigs_ng', ['id'], unique=False)
    op.create_table('reparaciones',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('jig_id', sa.Integer(), nullable=False),
    sa.Column('tecnico_id', sa.Integer(), nullable=False),
    sa.Column('fecha', sa.DateTime(), nullable=True),
    sa.Column('descripcion', sa.Text(), nullable=False),
    sa.Column('estado_anterior', sa.String(length=20), nullable=False),
    sa.Column('estado_nuevo', sa.String(length=20), nullable=False),
    sa.Column('sincronizado', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['jig_id'], ['jigs.id'], ),
    sa.ForeignKeyConstraint(['tecnico_id'], ['tecnicos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reparaciones_id'), 'reparaciones', ['id'], unique=False)
    op.create_table('solicitudes_registro',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario', sa.String(length=50), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('numero_empleado', sa.String(length=20), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('tipo_usuario', sa.String(length=20), nullable=True),
    sa.Column('firma_digital', sa.Text(), nullable=True),
    sa.Column('estado', sa.String(length=20), nullable=True),
    sa.Column('admin_id', sa.Integer(), nullable=True),
    sa.Column('fecha_solicitud', sa.DateTime(), nullable=True),
    sa.Column('fecha_respuesta', sa.DateTime(), nullable=True),
    sa.Column('comentarios_admin', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['admin_id'], ['tecnicos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_solicitudes_registro_id'), 'solicitudes_registro', ['id'], unique=False)
    op.create_index(op.f('ix_solicitudes_registro_numero_empleado'), 'solicitudes_registro', ['numero_empleado'], unique=True)
    op.create_index(op.f('ix_solicitudes_registro_usuario'), 'solicitudes_registro', ['usuario'], unique=True)
    op.create_table('validaciones',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('jig_id', sa.Integer(), nullable=True),
    sa.Column('tecnico_id', sa.Integer(), nullable=False),
    sa.Column('tecnico_asignado_id', sa.Integer(), nullable=True),
    sa.Column('fecha', sa.DateTime(), nullable=True),
    sa.Column('turno', sa.String(length=20), nullable=False),
    sa.Column('estado', sa.String(length=10), nullable=False),
    sa.Column('comentario', sa.Text(), nullable=True),
    sa.Column('cantidad', sa.Integer(), nullable=True),
    sa.Column('firma_digital', sa.Text(), nullable=True),
    sa.Column('sincronizado', sa.Boolean(), nullable=True),
    sa.Column('completada', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['jig_id'], ['jigs.id'], ),
    sa.ForeignKeyConstraint(['tecnico_asignado_id'], ['tecnicos.id'], ),
    sa.ForeignKeyConstraint(['tecnico_id'], ['tecnicos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_validaciones_id'), 'validaciones', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_validaciones_id'), table_name='validaciones')
    op.drop_table('validaciones')
    op.drop_index(op.f('ix_solicitudes_registro_usuario'), table_name='solicitudes_registro')
    op.drop_index(op.f('ix_solicitudes_registro_numero_empleado'), table_name='solicitudes_registro')
    op.drop_index(op.f('ix_solicitudes_registro_id'), table_name='solicitudes_registro')
    op.drop_table('solicitudes_registro')
    op.drop_index(op.f('ix_reparaciones_id'), table_name='reparaciones')
    op.drop_table('reparaciones')
    op.drop_index(op.f('ix_jigs_ng_id'), table_name='jigs_ng')
    op.drop_table('jigs_ng')
    op.drop_index(op.f('ix_damaged_labels_id'), table_name='damaged_labels')
    op.drop_table('damaged_labels')
    op.drop_index(op.f('ix_auditoria_pdfs_id'), table_name='auditoria_pdfs')
    op.drop_table('auditoria_pdfs')
    op.drop_index(op.f('ix_tecnicos_usuario'), table_name='tecnicos')
    op.drop_index(op.f('ix_tecnicos_numero_empleado'), table_name='tecnicos')
    op.drop_index(op.f('ix_tecnicos_id'), table_name='tecnicos')
    op.drop_table('tecnicos')
    op.drop_index(op.f('ix_jigs_id'), table_name='jigs')
    op.drop_index(op.f('ix_jigs_codigo_qr'), table_name='jigs')
    op.drop_table('jigs')
    # ### end Alembic commands ###

