"""expand_mainboard_conector_text_fields

Revision ID: 2eed5cdad06e
Revises: 6e4f1a2b3c5d
Create Date: 2026-02-08 22:26:27.941465

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2eed5cdad06e'
down_revision = '6e4f1a2b3c5d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('modelos_mainboard_conector', 'modelo_interno',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.Text(),
               existing_nullable=True)
    op.alter_column('modelos_mainboard_conector', 'tool_sw',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.Text(),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('modelos_mainboard_conector', 'tool_sw',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=100),
               existing_nullable=True)
    op.alter_column('modelos_mainboard_conector', 'modelo_interno',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=100),
               existing_nullable=True)
    # ### end Alembic commands ###

